### ISSUE TITLE
apt install clasp and apt install gringo

### ISSUE THREAD

**Issue by luckydoudouli** [hklarner/pyboolnet#102]
Error:
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

java has been installed and configured the environment.

![1665214277904](https://user-images.githubusercontent.com/115341102/194695794-5be1509d-5b42-4443-a6c9-77f5cb81abd5.jpg)

**Comment by hklarner** [comment]
sorry, I can't help you with this issue
