### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/dot'

### ISSUE THREAD

**Issue by luckydoudouli** [hklarner/pyboolnet#103]
What is the reason for the error?
![1665391518997](https://user-images.githubusercontent.com/115341102/194829389-33013782-2b46-463e-83a8-836e7b37ac8b.jpg)
![1665391572802](https://user-images.githubusercontent.com/115341102/194829422-ed27c386-212a-43ee-b25e-3dd2995f9abe.jpg)
![1665391633297](https://user-images.githubusercontent.com/115341102/194829460-69ff67fe-ddce-4d14-8732-14d3dce21a69.jpg)
![1665391681487](https://user-images.githubusercontent.com/115341102/194829476-58c0d45f-4334-4646-baaf-7c21dccc9c00.jpg)

**Comment by hklarner** [comment]
> What is the reason for the error?

I don't understand your question. It says right in the error message: `file not found: no such file /usr/bin/dot`.

If you have dot installed in a different path, you have to specify it in the settings.

Or just try `dot` instead of `/usr/bin/dot`.
