### ISSUE TITLE
igraph naming confusion

### ISSUE THREAD

**Issue by carissableker** [hklarner/pyboolnet#108]
In this package `igraph` is used to mean "interaction graph", however, [igraph](https://igraph.org/) is also a very popular graph analysis tool in Python (also R, Mathematica, and C++ ), with similarities to networkX. 

This is just to note the potential confusion.

**Comment by hklarner** [comment]
Yes, agreed. In case you need to run the igraph package alongside pyboolnet in a script where this might lead to confusions you can give an alias to igraph when you import it:

```
import igraph as igraphx
```
- see e.g. https://stackoverflow.com/questions/706595/can-you-define-aliases-for-imported-modules-in-python
