### ISSUE TITLE
Having issues troubleshooting bnet data issues 

### ISSUE THREAD

**Issue by MatthewCorney** [hklarner/pyboolnet#111]
Apologies for the mess of code but I thought it would be better to keep my troubleshooting in for clarity 

I have a bnet file however I am finding it difficult to import it in to pyboolnet, due to the logging I am not sure what the issue exactly is. nb I have changed the file type from .bnet to txt since github doesn't like the uploading of this format 

```
from pyboolnet.file_exchange import bnet2primes
path='model_inputs.txt'
bnetlist=[]
with open(path, 'r') as f:
    lines=f.readlines()
    for i, line in enumerate(lines):
        if i==0:
            pass
        else:
            line2= line.replace("\n",'')
            line2= line2.replace(",",', ')
            bnetlist.append(f'{line2}')
            print(i,line)
            bnet_now = "\n".join(bnetlist)
            primes = bnet2primes(bnet_now)
            if not primes:
                bnetlist.pop()
            # breaks at 68th entry
            # if i==67:
            #     break

```

[model_inputs.txt](https://github.com/hklarner/pyboolnet/files/14959120/model_inputs.txt)

Would love some suggestions about how to troubleshoot this

**Comment by hklarner** [comment]
Hi there. Most likely much too late to be helpful to you, but the cause of the error is that you defined the update function of `v_DDB1_CUL4A_complex` twice, namely in lines 46 and 69:

```
$ grep -n v_DDB1_CUL4A_complex model_inputs.txt
34:v_mTORC1_complex, (((v_DDB1_CUL4A_complex | v_sa11503_RHEB_lysosome) | v_Ragulator_SLC38A9_complex) & !v_sa11500_UCHL1_neuron)
46:v_DDB1_CUL4A_complex,0
69:v_DDB1_CUL4A_complex,0
```

The error message is unfortunately not clear but if you run `BNetToPrime_linux64` directly on your file you will see the error message:
```
$ ./pyboolnet/binaries/BNetToPrime/BNetToPrime_linux64 model_inputs.txt
BNetToPrime encountered an exception and aborted.
Exception message: "v_DDB1_CUL4A_complex already has a function."
```
