### ISSUE TITLE
Installation Error regarding "SafeConfigParser"

### ISSUE THREAD

**Issue by StueGrifn** [hklarner/pyboolnet#112]
Heyyo! I'm a grad student wanting to use PyBoolNet for a school project, and I have had a rough time installing PyBoolNet.

I use Windows 10. I have uninstall and reinstalled python, use Jupyter Notebook, updated pip, GitPython, and 'wheel', which was something another thread elsewhere recommended. This is the error that has stayed consistent throughout my changes:

`Traceback (most recent call last):`
`File "<string>", line 2, in <module>`
`File "<pip-setuptools-caller>", line 34, in <module>`
`File "C:\Users\17stb\AppData\Local\Temp\pip-req-build-vmfelc_9\setup.py", line 10, in <module>`
`from pyboolnet import VERSION`
`File "C:\Users\17stb\AppData\Local\Temp\pip-req-build-vmfelc_9\pyboolnet\__init__.py", line 17, in <module>`
`EXECUTABLES = read_executables()`
`^^^^^^^^^^^^^^^^^^`
`File "C:\Users\17stb\AppData\Local\Temp\pip-req-build-vmfelc_9\pyboolnet\helpers.py", line 24, in read_executables`
`config = configparser.SafeConfigParser()`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?`
`[end of output]`

Is there a command I can run to change the 'configparser' variable, or is there some more in-depth fix necessary?

Thank you!

**Comment by hklarner** [comment]
Hi @StueGrifn sorry for the late reply. Could you resolve your problem? What version of `pyboolnet` are you using? I might not be able to help you because I am not a Windows user.

**Comment by srikanth-iyer** [comment]
Hi there, I'm having the same problem on my University server on Linux
Can you help me resolve this?

**Comment by hklarner** [comment]
@srikanth-iyer I am preparing a fix. To help me understand the problem better, can you tell me your Python version?

**Comment by srikanth-iyer** [comment]
> @srikanth-iyer I am preparing a fix. To help me understand the problem better, can you tell me your Python version?

It's Python 3.12.3

**Comment by hklarner** [comment]
can you install version `3.0.14` and see if this fixes your problem?

```
pip3 install git+https://github.com/hklarner/pyboolnet@3.0.14
```

**Comment by srikanth-iyer** [comment]
@hklarner  yes that fixes it. thanks for your suggestion.
