### ISSUE TITLE
FileNotFoundError when running bnet2primes function from file_exchange

### ISSUE THREAD

**Issue by Samdeman35** [hklarner/pyboolnet#114]
I am having an issue with the  bnet2primes function from file_exchange. When I try to run this function using my created bnet file 
[simple_network_proposal.txt](https://github.com/hklarner/pyboolnet/files/15389366/simple_network_proposal.txt)
I get the following error when running the command primes = pyboolnet.file_exchange.bnet2primes('simple_network_proposal.txt'):

FileNotFoundError                         Traceback (most recent call last)
Cell In[63], line 3
      1 # network = open('simple_network_proposal.txt')
      2 # network = Path('simple_network_proposal.txt')
----> 3 primes = pyboolnet.file_exchange.bnet2primes('simple_network_proposal.txt')

File ~\AppData\Roaming\Python\Python311\site-packages\pyboolnet\file_exchange.py:49, in bnet2primes(bnet, fname_primes)
     21 def bnet2primes(bnet: str, fname_primes: Optional[str] = None) -> dict:
     22     """
     23     Generates and returns the prime implicants of a Boolean network in **boolnet** format.
     24     The primes are saved as a *json* file if *fname_primes* is given.
   (...)
     46         >>> primes = bnet2primes("Erk, !Mek \\n Raf, Ras & Mek", "mapk.primes")
     47     """
---> 49     primes = bnet_file2primes(fname_bnet=bnet) if os.path.isfile(bnet) else bnet_text2primes(text=bnet)
     51     if fname_primes and os.path.isfile(fname_primes):
     52         write_primes(primes=primes, fname_json=fname_primes)

File ~\AppData\Roaming\Python\Python311\site-packages\pyboolnet\external\bnet2primes.py:59, in bnet_file2primes(fname_bnet)
     56     return
     58 cmd = [CMD_BNET2PRIMES, fname_bnet]
---> 59 proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
     60 out, err = proc.communicate()
     61 out = out.decode()

File C:\ProgramData\anaconda3\Lib\subprocess.py:1026, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize, process_group)
   1022         if self.text_mode:
   1023             self.stderr = io.TextIOWrapper(self.stderr,
   1024                     encoding=encoding, errors=errors)
-> 1026     self._execute_child(args, executable, preexec_fn, close_fds,
   1027                         pass_fds, cwd, env,
   1028                         startupinfo, creationflags, shell,
   1029                         p2cread, p2cwrite,
   1030                         c2pread, c2pwrite,
   1031                         errread, errwrite,
   1032                         restore_signals,
   1033                         gid, gids, uid, umask,
   1034                         start_new_session, process_group)
   1035 except:
   1036     # Cleanup if the child failed starting.
   1037     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File C:\ProgramData\anaconda3\Lib\subprocess.py:1538, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session, unused_process_group)
   1536 # Start the process
   1537 try:
-> 1538     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1539                              # no special security
   1540                              None, None,
   1541                              int(not close_fds),
   1542                              creationflags,
   1543                              env,
   1544                              cwd,
   1545                              startupinfo)
   1546 finally:
   1547     # Child is launched. Close the parent's copy of those pipe
   1548     # handles that only the child should have open.  You need
   (...)
   1551     # pipe will not close when the child process exits and the
   1552     # ReadFile will hang.
   1553     self._close_pipe_fds(p2cread, p2cwrite,
   1554                          c2pread, c2pwrite,
   1555                          errread, errwrite)

FileNotFoundError: [WinError 2] The system cannot find the file specified

However, when I try to load in the file using file = open('simple_network_proposal.txt', 'r') I do not get any errors and I am able to read the lines in the file.  I am using Jupyter Notebook.

**Comment by hklarner** [comment]
try the absolute path to your file

**Comment by Samdeman35** [comment]
@hklarner I am getting the same error using the absolute path primes = pyboolnet.file_exchange.bnet2primes('C:/Users/Sam/Jupyter notebooks/Master Thesis/simple_network_proposal.txt')

FileNotFoundError                         Traceback (most recent call last)
Cell In[4], line 3
      1 # network = open('simple_network_proposal.txt')
      2 # network = Path('simple_network_proposal.txt')
----> 3 primes = pyboolnet.file_exchange.bnet2primes('C:/Users/Sam/Jupyter notebooks/Master Thesis/simple_network_proposal.txt')

File ~\AppData\Roaming\Python\Python311\site-packages\pyboolnet\file_exchange.py:49, in bnet2primes(bnet, fname_primes)
     21 def bnet2primes(bnet: str, fname_primes: Optional[str] = None) -> dict:
     22     """
     23     Generates and returns the prime implicants of a Boolean network in **boolnet** format.
     24     The primes are saved as a *json* file if *fname_primes* is given.
   (...)
     46         >>> primes = bnet2primes("Erk, !Mek \\n Raf, Ras & Mek", "mapk.primes")
     47     """
---> 49     primes = bnet_file2primes(fname_bnet=bnet) if os.path.isfile(bnet) else bnet_text2primes(text=bnet)
     51     if fname_primes and os.path.isfile(fname_primes):
     52         write_primes(primes=primes, fname_json=fname_primes)

File ~\AppData\Roaming\Python\Python311\site-packages\pyboolnet\external\bnet2primes.py:59, in bnet_file2primes(fname_bnet)
     56     return
     58 cmd = [CMD_BNET2PRIMES, fname_bnet]
---> 59 proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
     60 out, err = proc.communicate()
     61 out = out.decode()

File C:\ProgramData\anaconda3\Lib\subprocess.py:1026, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize, process_group)
   1022         if self.text_mode:
   1023             self.stderr = io.TextIOWrapper(self.stderr,
   1024                     encoding=encoding, errors=errors)
-> 1026     self._execute_child(args, executable, preexec_fn, close_fds,
   1027                         pass_fds, cwd, env,
   1028                         startupinfo, creationflags, shell,
   1029                         p2cread, p2cwrite,
   1030                         c2pread, c2pwrite,
   1031                         errread, errwrite,
   1032                         restore_signals,
   1033                         gid, gids, uid, umask,
   1034                         start_new_session, process_group)
   1035 except:
   1036     # Cleanup if the child failed starting.
   1037     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File C:\ProgramData\anaconda3\Lib\subprocess.py:1538, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session, unused_process_group)
   1536 # Start the process
   1537 try:
-> 1538     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1539                              # no special security
   1540                              None, None,
   1541                              int(not close_fds),
   1542                              creationflags,
   1543                              env,
   1544                              cwd,
   1545                              startupinfo)
   1546 finally:
   1547     # Child is launched. Close the parent's copy of those pipe
   1548     # handles that only the child should have open.  You need
   (...)
   1551     # pipe will not close when the child process exits and the
   1552     # ReadFile will hang.
   1553     self._close_pipe_fds(p2cread, p2cwrite,
   1554                          c2pread, c2pwrite,
   1555                          errread, errwrite)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Samdeman35** [comment]
Hi @hklarner I don't have a binaries file in ~\AppData\Roaming\Python\Python311\site-packages\pyboolnet\binaries. If I run the dependencies check I get the following error:

(base) PS C:\Users\Sam> pyboolnet check-dependencies
pyboolnet version: 3.0.13
INFO gringo command = C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\pyboolnet\binaries\gringo-4.4.0-x86-linux\gringo --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\Scripts\pyboolnet.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\pyboolnet\cli\commands\check_dependencies.py", line 11, in check_dependencies
    check_all_dependencies()
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\pyboolnet\cli\check_dependencies.py", line 13, in check_all_dependencies
    check_gringo_responds()
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\pyboolnet\cli\check_dependencies.py", line 28, in check_gringo_responds
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by hklarner** [comment]
What is the output of
```
import platform
print(platform.system())
```

And what is the value of
```
import os
"CONDA_BUILD" in os.environ
```

**Comment by Samdeman35** [comment]
(base) PS C:\Users\Sam> python
Python 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print(platform.system())
Windows
>>> import os
>>> "CONDA_BUILD" in os.environ
False

**Comment by hklarner** [comment]
In the other issue you reported that

> @hklarner thank you for the quick fix! However, when I try to install the new version using the pip command in Anaconda, the binaries folder is missing, which means I can't import PyBoolNet.

So you are saying that previously (version `3.0.12`) the binaries folder was present but now (version `3.0.13`) it isn't?

> I also have this issue on Windows within Google Colab.

Could it be that you never had a binaries folder? I.e. that pyboolnet never worked for you ("on Windows withing Google Colab")?

**Comment by Samdeman35** [comment]
In the 3.0.12 version the binaries folder was also not present, but when I revert to the 3.0.11 version, the binaries folder is present. The issue I had with with 3.0.11 was with gringo not working, but the rest of the package still worked for me.

**Comment by hklarner** [comment]
Can you post the complete output of
```
pip install --force-reinstall git+https://github.com/hklarner/pyboolnet@3.0.13
```

**Comment by hklarner** [comment]
Can you go to your pyboolnet folder (`C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\pyboolnet`) and post the contents as a tree of files:
- https://stackoverflow.com/questions/9518646/tree-view-of-a-directory-folder-in-windows
```
tree /f 
```

**Comment by Samdeman35** [comment]
[tree.txt](https://github.com/hklarner/pyboolnet/files/15401343/tree.txt)

**Comment by hklarner** [comment]
Copy the windows binary folder to your installation manually. 1) download source code
- https://github.com/hklarner/pyboolnet/archive/refs/tags/3.0.13.zip

Copy this folder into your pyboolnet installation folder and rename it to `binaries`
- https://github.com/hklarner/pyboolnet/tree/3.0.13/binaries/win64

**Comment by Samdeman35** [comment]
Thank you that worked! I am having the problem now that all my dependencies are in the my Python311 folder instead of the anaconda3 folder because of the --force-reinstall, Jupyter notebook is still looking in the anaconda3 folder for the dependencies. Can I reverse this somehow?

**Comment by Samdeman35** [comment]
To make this problem a bit more clear, I am getting a FileNotFoundError again when running pyboolnet.interaction_graphs.igraph2image(igraph, 'simple_network.png')

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[33], line 1
----> 1 pyboolnet.interaction_graphs.igraph2image(igraph, 'simple_network.png')

File ~\AppData\Roaming\Python\Python311\site-packages\pyboolnet\interaction_graphs.py:212, in igraph2image(igraph, fname_image, layout_engine)
    195 def igraph2image(igraph: networkx.DiGraph, fname_image: str, layout_engine="fdp"):
    196     """
    197     Creates an image file from *igraph* using :ref:`installation_graphviz` and the force directed layout engine *fdp*.
    198     To find out which file formats are supported call ``$ dot -T?``.
   (...)
    209           >>> igraph2image(igraph, "mapk_igraph.svg")
    210     """
--> 212     digraph2image(igraph, fname_image, layout_engine=layout_engine)

File ~\AppData\Roaming\Python\Python311\site-packages\pyboolnet\digraphs.py:273, in digraph2image(digraph, fname_image, layout_engine)
    270 cmd = [LAYOUT_ENGINES[layout_engine], "-T" + filetype, "-o", fname_image]
    271 dotfile = digraph2dot(digraph)
--> 273 proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    274 out, err = proc.communicate(input=dotfile.encode())
    275 proc.stdin.close()

File C:\ProgramData\anaconda3\Lib\subprocess.py:1026, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize, process_group)
   1022         if self.text_mode:
   1023             self.stderr = io.TextIOWrapper(self.stderr,
   1024                     encoding=encoding, errors=errors)
-> 1026     self._execute_child(args, executable, preexec_fn, close_fds,
   1027                         pass_fds, cwd, env,
   1028                         startupinfo, creationflags, shell,
   1029                         p2cread, p2cwrite,
   1030                         c2pread, c2pwrite,
   1031                         errread, errwrite,
   1032                         restore_signals,
   1033                         gid, gids, uid, umask,
   1034                         start_new_session, process_group)
   1035 except:
   1036     # Cleanup if the child failed starting.
   1037     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File C:\ProgramData\anaconda3\Lib\subprocess.py:1538, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session, unused_process_group)
   1536 # Start the process
   1537 try:
-> 1538     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1539                              # no special security
   1540                              None, None,
   1541                              int(not close_fds),
   1542                              creationflags,
   1543                              env,
   1544                              cwd,
   1545                              startupinfo)
   1546 finally:
   1547     # Child is launched. Close the parent's copy of those pipe
   1548     # handles that only the child should have open.  You need
   (...)
   1551     # pipe will not close when the child process exits and the
   1552     # ReadFile will hang.
   1553     self._close_pipe_fds(p2cread, p2cwrite,
   1554                          c2pread, c2pwrite,
   1555                          errread, errwrite)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by hklarner** [comment]
> Thank you that worked! I am having the problem now that all my dependencies are in the my Python311 folder instead of the anaconda3 folder because of the --force-reinstall, Jupyter notebook is still looking in the anaconda3 folder for the dependencies. Can I reverse this somehow?

Sorry, but I can't offer support for your setup.

**Comment by Samdeman35** [comment]
I understand, I will try to find the solution myself. Thank you so much for all your help and quick responses!

**Comment by Samdeman35** [comment]
I wanted to mention for people who might have a problem with a FileNotFoundError because of Graphviz, running these 4 lines at the beginning of the script fixed the issue for me:

import pyboolnet.digraphs as digraphs
digraphs.LAYOUT_ENGINES['fdp'] = 'fdp'
digraphs.LAYOUT_ENGINES['dot'] = 'dot'
digraphs.LAYOUT_ENGINES['neato'] = 'neato'
