### ISSUE TITLE
we need libtinfo.so.5 when run nusmv but we only have libtinfo.so.6

### ISSUE THREAD

**Issue by yujcccc** [hklarner/pyboolnet#116]
When I run attractors.find_attractor_state_by_randomwalk_and_ctl,
Program gives an error:ERROR nusmv did not respond with return code 0: cmd=/home/yjc/anaconda3/lib/python3.12/site-packages/pyboolnet/binaries/NuSMV-a/NuSMVa_linux64 -dcx -dynamic -df -coi /tmp/pyboolnet_p54y3to3, return_code=127 output='', error=b'/home/yjc/anaconda3/lib/python3.12/site-packages/pyboolnet/binaries/NuSMV-a/NuSMVa_linux64: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory\n'

I can't find libtinfo.so.5 but find libtinfo.so.6:
/home/yjc/anaconda3/lib/libtinfo.a
/home/yjc/anaconda3/lib/libtinfo.so
/home/yjc/anaconda3/lib/libtinfo.so.6
/home/yjc/anaconda3/lib/libtinfo.so.6.4
/usr/lib/x86_64-linux-gnu/libtinfo.so.6
/usr/lib/x86_64-linux-gnu/libtinfo.so.6.4
/usr/share/doc/libtinfo6
/usr/share/doc/libtinfo6/changelog.Debian.gz
/usr/share/doc/libtinfo6/copyright
/var/lib/dpkg/info/libtinfo6:amd64.list
/var/lib/dpkg/info/libtinfo6:amd64.md5sums
/var/lib/dpkg/info/libtinfo6:amd64.shlibs
/var/lib/dpkg/info/libtinfo6:amd64.symbols
/var/lib/dpkg/info/libtinfo6:amd64.triggers

And I can't download libtinso5 through apt. Is there a version problem here?

**Comment by hklarner** [comment]
try creating a symbolic link `libtinfo.so.5` -> `libtinfo.so.6`.

**Comment by yujcccc** [comment]
I have done it twice:
sudo ln -s /home/yjc/anaconda3/lib/libtinfo.so.6 /home/yjc/anaconda3/lib/libtinfo.so.5

sudo ln -s /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5

The former has no effect, and the latter will only give another error:

ERROR nusmv did not respond with return code 0: cmd=/home/yjc/anaconda3/lib/python3.12/site-packages/pyboolnet/binaries/NuSMV-a/NuSMVa_linux64 -dcx -dynamic -df -coi /tmp/pyboolnet_rb3j253v, return_code=1 output='', error=b"/home/yjc/anaconda3/lib/python3.12/site-packages/pyboolnet/binaries/NuSMV-a/NuSMVa_linux64: /lib/x86_64-linux-gnu/libtinfo.so.5: version `NCURSES_TINFO_5.0.19991023' not found (required by /home/yjc/anaconda3/ lib/python3.12/site-packages/pyboolnet/binaries/NuSMV-a/libreadline.so.6)\n"

**Comment by hklarner** [comment]
Can you try the answer in this SO post?

- https://stackoverflow.com/questions/72103046/libtinfo-so-6-no-version-information-available-message-using-conda-environment

What OS are you on?

**Comment by yujcccc** [comment]
Thanks for your answer, I have updated the new apt source and installed libtinfo5 through apt and the program is running again. I ran pyboolnet well last year. I suspect that it was caused by the change of apt source when I upgraded ubuntu from 22 to 24.
