### ISSUE TITLE
Format of images of graphs

### ISSUE THREAD

**Issue by RSchwieger** [hklarner/PyBoolNet#13]
In which formats I can save my images of the graphs created by PyBoolNet? Is it possible to save the graphs in EPS-format?

**Comment by hklarner** [comment]
That depends on what your *dot* installation is capable of. You should be able to create *eps* files simply by using the corresponding file extension for the *FnameIMAGE* parameter, e.g.:

`igraph2image(igraph, "mapk_igraph.eps")`

For more info see the reference of the function you are using in the [manual](https://github.com/hklarner/PyBoolNet/blob/master/Docs/Sphinx/build/latex/PyBoolNet.pdf).
