### ISSUE TITLE
primes2bns and node with constant value 1 assumed to be 0 in bns

### ISSUE THREAD

**Issue by marcomoretto** [hklarner/PyBoolNet#15]
`primes2bns` method seems not to take correctly into consideration nodes with constant values. This might be problematic given that `bns` assumes 0 as default value, while one might want to have 1 as constant value. For example:
```
v1, v1|v3
v2, 1
v3, v1&!v2 | !v1&v2
```
generates the following bns for v2
```
# v2
.n 2 0 
 1
```
Feeding this file to `bns` would give a warning stating that v2 is assumed to be 0. To temporarily solve this issue for my case I overloaded the `primes2bns` with the following code:
```
def primes2bns(Primes, FnameBNS):
   [...]
   names_sorted = sorted(Primes)
   lines = ['# '+', '.join(names_sorted),'']
   lines+= ['.v %i'%len(names_sorted),'']
    
   ig = PyBoolNet.InteractionGraphs.primes2igraph(Primes)
   for i, name in enumerate(names_sorted):
        i=i+1
        lines+= ['# %s'%name]
        regulators = sorted(ig.predecessors(name))
        nregs = len(regulators)
        iregs = ' '.join([str(names_sorted.index(reg)+1) for reg in regulators])
        ### -- begin workaround -- ###
        if nregs == 0:
            regulators.append(i)
            nregs = len(regulators)
            iregs = ' '.join([str(reg) for reg in regulators])
        ### -- end workaround -- ###
        lines+= ['.n {index} {number_regs} {ids_regs}'.format(index=i, number_regs=nregs, ids_regs=iregs)]

        for v in [0,1]:
            [...]
```
The end result for v2 is:
```
# v2
.n 2 1 2
- 1
```

**Comment by hklarner** [comment]
Well spotted! The error is actually just the space in front of the `1` in
```
# v2
.n 2 0 
 1
```
I fixed that in on the branch [develop](https://github.com/hklarner/PyBoolNet/tree/develop), see this [commit](https://github.com/hklarner/PyBoolNet/commit/774bd7fe7539f0bac875697b4b66d7a93fac7013).
If I have time I will publish a new release of PyBoolNet today or tomorrow.

**Comment by ilmorez** [comment]
Ahh that is great! I'm not an expert of `bns` syntax so I followed what I assumed to be the safest way :-)

**Comment by hklarner** [comment]
the only specification I found about this file type, which is in fact called *cnet*, is on the homepage of the *bns* tool: https://people.kth.se/~dubrova/BNS/user_manual.html
