### ISSUE TITLE
Incorrect filenames in settings.cfg for linux64

### ISSUE THREAD

**Issue by margrietpalm** [hklarner/PyBoolNet#17]
The paths for numsv, gringo, clasp, and bnet2prime in the settings.cfg for linux64 are incorrect. This should be:
```
nusmv           = ./NuSMV-a/NuSMVa_linux64
gringo          = ./gringo-4.4.0/gringo_linux64
clasp           = ./clasp-3.1.1/clasp-3.1.1-x86_64-linux
bnet2prime      = ./BNetToPrime/BNetToPrime_linux64
```
[This patch fixes the problem](https://github.com/hklarner/PyBoolNet/files/1431434/patch.txt)

**Comment by hklarner** [comment]
thanks for spotting this. i am about to release a new version that will fix this issue.
