### ISSUE TITLE
Mention incompatibility with NetworkX 2.0 in manual

### ISSUE THREAD

**Issue by margrietpalm** [hklarner/PyBoolNet#18]
NetworkX recently released a new major version (NetworkX 2.0) that is not fully backward compatiable with NetworkX 1.X (see the [migration guide](https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html)). I just experienced that PyBoolNet does not work with NetworkX2.0, although this was not mentioned in the manual. A little warning would save future users quite some time.

FYI: I'm now using PyBoolNet with NetworkX1.11 and this seems to work well.

**Comment by hklarner** [comment]
Thanks, I will take a look. I can possibly make it work on both versions of networkx. Can you tell me which PyBoolNet function failed for you with networkx2.0?

Also, I just released PyBoolNet 2.2.0 which has two more modules: [Basins](https://github.com/hklarner/PyBoolNet/blob/master/PyBoolNet/Basins.py) for basins of attraction and [BooleanExpressions](https://github.com/hklarner/PyBoolNet/blob/master/PyBoolNet/BooleanExpressions.py) for minimizing Boolean expressions with [espresso](http://www.ecs.umass.edu/ece/labs/vlsicad/ece667/links/espresso.html). Might be interesting for you. These modules are still under development and feedback is greatly appreciated. What version of PyBoolNet are you currently using?

Finally, if there is a particular task you are using PyBoolNet for and need help with then don't hesitate opening an issue for that. I would be happy to create examples scripts with you for use cases that will also help other people find their way into using PyBoolNet. For whatever task you have in mind we can probably find a suitable toy example from the [Repository](https://github.com/hklarner/PyBoolNet/tree/master/PyBoolNet/Repository).

**Comment by margrietpalm** [comment]
> Thanks, I will take a look. I can possibly make it work on both versions of networkx. Can you tell me which PyBoolNet function failed for you with networkx2.0?

We are running PyBoolNet 2.11.0 and ran into problems with the example code from section 2.2 of PyBoolNet's manual:
```
igraph.edge["v1"]["v3"]["sign"]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-94b099739f55> in <module>()
----> 1 igraph.edge["v1"]["v3"]["sign"]

AttributeError: 'DiGraph' object has no attribute 'edge'
```
and
```
IGs.igraph2image(igraph, "example02_igraph.pdf")
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-23-f5da3be8273c> in <module>()
----> 1 IGs.igraph2image(igraph, "example02_igraph.pdf")

$HOME/.local/lib/python2.7/site-packages/PyBoolNet/InteractionGraphs.pyc in igraph2image(IGraph, FnameIMAGE, Silent)
    133     """
    134 
--> 135     PyBoolNet.Utility.DiGraphs.digraph2image(IGraph, FnameIMAGE, LayoutEngine="dot", Silent=Silent)
    136 
    137 

$HOME/.local/lib/python2.7/site-packages/PyBoolNet/Utility/DiGraphs.pyc in digraph2image(DiGraph, FnameIMAGE, LayoutEngine, Silent)
    245 
    246     cmd = [LAYOUT_ENGINES[LayoutEngine], "-T"+filetype, "-o", FnameIMAGE]
--> 247     dotfile = digraph2dot(DiGraph, FnameDOT=None)
    248 
    249     proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

$HOME/.local/lib/python2.7/site-packages/PyBoolNet/Utility/DiGraphs.pyc in digraph2dot(DiGraph, FnameDOT)
    174         return
    175 
--> 176     assert(type(DiGraph.nodes()[0])==str)
    177 
    178     lines = ['digraph {']

$HOME/anaconda2/lib/python2.7/site-packages/networkx/classes/reportviews.pyc in __getitem__(self, n)
    176 
    177     def __getitem__(self, n):
--> 178         return self._nodes[n]
    179 
    180     # Set methods

KeyError: 0
```
It seems that both of these issues have to do with the following changes in NetworkX:

> One View example is G.nodes (or G.nodes()) which now returns a dict-like NodeView while G.nodes_iter() has been removed. Similarly for views with G.edges and removing G.edges_iter. The Graph attributes G.node and G.edge have been removed in favor of using G.nodes[n] and G.edges[u, v].

This looks like a quite big change to me, so I imagine making the PyBoolNet compatible to both NetworkX versions will be quite some work. 

> Finally, if there is a particular task you are using PyBoolNet for and need help with then don't hesitate opening an issue for that. I would be happy to create examples scripts with you for use cases that will also help other people find their way into using PyBoolNet. For whatever task you have in mind we can probably find a suitable toy example from the Repository.

I'm just helping out one of our MSc students with getting PyBoolNet working and I don't know all the details of his project. But, it is good to know that you're actively supporting the package.

**Comment by ninakersten** [comment]
We had the same problem.
sudo pip3 install -lv networkx==1.11

worked for us

**Comment by hklarner** [comment]
PyBoolNet version `2.2.4` (May 2018) is compatible with networkx 2
