### ISSUE TITLE
compatibility with python 3

### ISSUE THREAD

**Issue by RSchwieger** [hklarner/PyBoolNet#19]
In the basins module seems to be a compatibility issue with python 3. I get the following error message:

  File "/home/robert/.local/lib/python3.6/site-packages/PyBoolNet/Basins.py", line 1025
    print colors
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int colors)?

**Comment by hklarner** [comment]
can not reproduce, must have been fixed since
