### ISSUE TITLE
Wrong path for clasp-3.2.0_mac64 in settings.cfg

### ISSUE THREAD

**Issue by djwooten** [hklarner/PyBoolNet#26]
For mac, settings.cfg lists the path for clasp as `./clasp-3.1.1/clasp-3.2.0_mac64`, but it should be `./clasp-3.2.0/clasp-3.2.0_mac64`

**Comment by hklarner** [comment]
thank you. can confirm. see if the attached 2.2.5 works. if so, I will upload it to the releases section.

[PyBoolNet-2.2.5_mac64.tar.gz](https://github.com/hklarner/PyBoolNet/files/3731602/PyBoolNet-2.2.5_mac64.tar.gz)

**Comment by hklarner** [comment]
@djwooten If the above file works for you please let me know. I will then update the [releases section](https://github.com/hklarner/PyBoolNet/releases).
