### ISSUE TITLE
"eqntott/eqntott_mac64" is missing for mac64

### ISSUE THREAD

**Issue by ghost** [hklarner/PyBoolNet#27]
Hello, the executable file "eqntott/eqntott_mac64" is missing for "Dependecies/mac64". Could you please upload it?

**Comment by hklarner** [comment]
uff. you're right. The sources are here:

- https://code.google.com/archive/p/eqntott/downloads

Problem is: I don't have a mac, so I can't compile / test for mac. Could you help out?

**Comment by hklarner** [comment]
No worries, I found the file on a branch. I will add it tomorrow.

**Comment by hklarner** [comment]
No worries, I found the file on a branch. I will add it tomorrow.

**Comment by hklarner** [comment]
Can you please confirm that PyBoolNet 2.2.6 fixes the issue?

https://github.com/hklarner/PyBoolNet/releases/tag/2.2.6

**Comment by sss-c** [comment]
Yes. It works now. Thank you!
