### ISSUE TITLE
eqntott missing in windows release

### ISSUE THREAD

**Issue by jcrozum** [hklarner/PyBoolNet#32]
The eqntott directory is not in the dependency directory on the windows 64 version. It does appear to be in one of the other branches.

**Comment by jcrozum** [comment]
The espresso executable seems to be missing too.

**Comment by hklarner** [comment]
can confirm. am looking into it..

**Comment by hklarner** [comment]
https://github.com/hklarner/PyBoolNet/releases/tag/2.2.7

Does this work for you?

**Comment by jcrozum** [comment]
Unfortunately not. Running the BooleanLogic module (which works fine in Linux) gives the following error in Windows:

.\BooleanLogic.py:10: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = PyBoolNet.Utility.Misc.myconfigparser.SafeConfigParser()
some basic tests
b''
b'/usr/bin/eqntott_win64: 0: syntax error\n... \x00\x00 ...\n      ^\n'

Call to "eqntott" resulted in return code 1
Traceback (most recent call last):
  File ".\BooleanLogic.py", line 186, in <module>
    res = are_mutually_exclusive(A="x & !Y", B="Y")
  File ".\BooleanLogic.py", line 22, in are_mutually_exclusive
    res = minimize_espresso("({A}) & ({B})".format(A=A,B=B))
  File ".\BooleanLogic.py", line 154, in minimize_espresso
    eqntott_out = run_eqntott(eqntott_cmd, eqntott_in)
  File ".\BooleanLogic.py", line 77, in run_eqntott
    _eqntott_error(eqntott, eqntott_out, eqntott_err)
  File ".\BooleanLogic.py", line 59, in _eqntott_error
    raise Exception
Exception

**Comment by hklarner** [comment]
oh no

**Comment by hklarner** [comment]
I am wondering how this syntax error comes up. I don't use windows. Could you help? Could you run the bin eqntott with some input?

**Comment by jcrozum** [comment]
I was unable to get the bin to run properly from the command line. However, I compiled the source from here using gcc & make in CygWin: https://code.google.com/archive/p/eqntott/downloads and replaced the exe with my newly compiled one, which did work. Here it is: 
[eqntott_win64.zip](https://github.com/hklarner/PyBoolNet/files/4303902/eqntott_win64.zip)

As an aside, I don't think all that extra stuff in the bin and lib folders is necessary; the .exe should work as a standalone.

I replaced the exe and commented out the eqntott_cmd += ['/dev/stdin'] line in BooleanLogic.py (line #152), as there is no /dev/stdin in windows. I'm not sure if that change would mess things up in Linux or Mac, but now it runs in Windows! Here's the output, which includes a deprecation warning

:

```
.\BooleanLogic.py:10: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = PyBoolNet.Utility.Misc.myconfigparser.SafeConfigParser()
some basic tests
OK
```

**Comment by hklarner** [comment]
>  I compiled the source from here using gcc & make in CygWin

Great!

> I replaced the exe and commented out the eqntott_cmd += ['/dev/stdin'] line in BooleanLogic.py

Yes, that would mess up things in Linux I think. I guess we could add an if statement that detects the os. Eg with

https://stackoverflow.com/questions/1325581/how-do-i-check-if-im-running-on-windows-in-python

Ill open a branch with your binaries and the if-statement. Would be great if you could test that it runs on windows. Ill keep you posted.

**Comment by jcrozum** [comment]
Any update on this? I'd be happy to test the new branch on Windows once it's opened.

**Comment by hklarner** [comment]
Thanks for getting back on this. I am too busy this week, i think. I will put it in my calendar though. Maybe the weekend. Will get back to you!

**Comment by hklarner** [comment]
@jcrozum 
[PyBoolNet-2.2.8_win64.tar.gz](https://github.com/hklarner/PyBoolNet/files/4399252/PyBoolNet-2.2.8_win64.tar.gz) can you try this version?

**Comment by jcrozum** [comment]
It works on Windows now! Thanks!
