### ISSUE TITLE
Networkx 2.4 Incompatibility in Utility.DiGraphs.py

### ISSUE THREAD

**Issue by jcrozum** [hklarner/PyBoolNet#33]
DiGraph.node is removed in networkx version 2.4 and replaced by DiGraph.nodes. Replacing 

```
cgraph.node[target]["depth"] = depth
cgraph.node[target]["id"]	= ID

```
with

```
cgraph.nodes[target]["depth"] = depth
cgraph.nodes[target]["id"]	= ID
```

in Utility/DiGraphs.py seems to fix the missing attribute error I was getting. I haven't noticed the issue anywhere else, but I haven't looked very hard.

**Comment by hklarner** [comment]
I am aware that PyBoolNet does not work with the latest networkx. Maybe I should also update dependencies and add a requirements.txt.

Thanks for opening the issue.
