### ISSUE TITLE
"File not Found" Error on Docs Manual Example in Windows 10

### ISSUE THREAD

**Issue by VitaminBrad** [hklarner/PyBoolNet#34]
To whom it may concern,

Thank you for developing this tool!

I am getting the following error however when I try to run the line

`PyBoolNet.InteractionGraphs.create_image(primes, "igraph.pdf")`

from page 12 of the Documentation/Quick Manual:

![](https://imgur.com/1wEuDyZ.png)

The same error occurs when I call `PyBoolNet.InteractionGraphs.create_image(primes, "igraph2.pdf", Styles=["sccs", "anonymous"])`

Therefore, it appears to be occuring on the line 

`proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`

from the script PyBoolNet\Utility\DiGraphs.py

I have tried setting `shell = True` as mentioned [here](https://stackoverflow.com/questions/3022013/windows-cant-find-the-file-on-subprocess-call/32799942#32799942) , however, this did not solve the problem.

Thank you very much for your time and attention!

P.S.
I'm not sure if it is related at all, but this message also appears in the top of my Jupyter Notebook: ![](https://imgur.com/roUCXsN.png)

**Comment by hklarner** [comment]
Hi  @VitaminBrad it looks like you haven't got graphviz installed (FileNotFoundError) did you check 1.4 of the manual? also please run 

```
$ python
>>> import PyBoolNet
>>> PyBoolNet.Tests.Dependencies.run()
```

and post the results here.

**Comment by VitaminBrad** [comment]
Hi @hklarner ! Thanks so much for the response!

Here was the result:

![](https://imgur.com/KUJ4Bow.png)

Best,

**Comment by hklarner** [comment]
uh.

1. I am not talking about the python graphviz package. Didd you read the manual section 1.4? It tells you how to install for windows. You have to download stuff.

2. you're running pyboolnet from within jupyter? i have never done that and dont understand the error message.
