### ISSUE TITLE
Function inputs in functions2mindnf 

### ISSUE THREAD

**Issue by carissableker** [hklarner/PyBoolNet#42]
I have a use case where I had to change [`functions2mindnf`](https://github.com/hklarner/PyBoolNet/blob/1eb9a00f559cda6d67dc21341d09ef8e625ed35f/PyBoolNet/QuineMcCluskey.py#L94) in PyBoolNet/QuineMcCluskey.py. I thought I would outline it here. 

For prime calculations I am producing the the update functions in a generalised way, and the input to each update  function is the complete network state (a length n list). Unfortunately PyBoolNet will then assume the function depends on the entire network. There may be a work around, but my fix was to make a minimal change that allows explicitly defining the node dependencies when needed. 

### Proposed change 
The original is:
https://github.com/hklarner/PyBoolNet/blob/1eb9a00f559cda6d67dc21341d09ef8e625ed35f/PyBoolNet/QuineMcCluskey.py#L130

And I propose the following: 
```python
        if hasattr(func, 'depends'):
            inputs = func.depends
        else:
            inputs = inspect.getargspec(func).args
```

To use it, one can add a `depends` attribute to the function, e.g.

```python
f = lambda x, y, *args: x or y
f(1, 1) # 1
f(0, 0) # 0
f(0, 0, 1, 1) # 0

f.depends = ['x', 'y']

```

And `functions2mindnf` will use the attribute to decide on the node dependencies instead of deducing them from the function arguments. 

### Example use 

Here is a dummy example of why I  needed this change (my actual use-case is of much larger networks, and more complicated update functions). 
```python
from PyBoolNet import QuineMcCluskey as QMC
import numpy as np

# Setup
data =  np.array([[1, 0, 0],
                [1, 0, 1], 
                [0, 0, 1]])
n = 3
idx = {f"node{x}":x for x in range(n)}

# the function producer
def update_function(data, node):
        # this is a dummy example where node_state is a function 
        # of `data` and the network state
        
        # actual node dependencies
        args = [f"node{x}" for x in np.nonzero(data[idx[node]])[0]]

        def func(*func_input):
                # derive the network state from the input
                network_state = [0]*n
                for other_node, other_node_state in zip(args, func_input):
                    network_state[idx[other_node]] = other_node_state
                
                # calculate the node state
                node_state = np.matmul(data[idx[node]], network_state)
                return node_state
            
        func.depends = args   
        return func

funcs = {node:update_function(data,  node) for node in idx.keys()}
primes = QMC.functions2primes(funcs)
```

**Comment by hklarner** [comment]
It might be possible to get the same result by changing the input to `functions2primes` instead of the code of `functions2primes`. Let's look at your example. You define a matrix

```python
data =  np.array([[1, 0, 0],
                  [1, 0, 1], 
                  [0, 0, 1]])
```
and a update rule
```python
node_state = np.matmul(data[idx[node]], network_state)
```
for three nodes. First question, this network is not Boolean, right? For `network_state=[1, 0, 1]` and `node=1` this will return `1+1=2`.
Second question, is there a way to transform the matrix into a dict of functions that has the correct dependencies? Something like:
```python
{
'f1': lambda x1: x1,
'f2': lambda x1, x2: x1 + x2,
'f3': lambda x3: x3
}
```

If that's the case you could add an adapter that takes a matrix and transforms into a dict input functions for `functions2primes`.

**Comment by carissableker** [comment]
First, I am working with Boolean networks, sorry my example is a bit rough. 

Second, I think in general not. In this particular example, yes, I could see a way of automating a dict of lambdas as you suggest. However in the actual case the update rule is more complicated and may change for different applications.  Therefore I am aiming for a general solution when I am "mass producing" functions. 

I can see that this may be a very niche application and maybe not relevant enough, so I will close this issue.
