### ISSUE TITLE
Using stg2image to plot a MultiDiGraph

### ISSUE THREAD

**Issue by nanls** [hklarner/PyBoolNet#43]
Hi, 

I am trying to use `PyBoolNet.StateTransitionGraphs.stg2image` to plot a stg stored in a `networkx.MultiDiGraph` instead of a `networkx.DiGraph`. 

I really need a `networkx.MultiDiGraph` because my stg can contain **parallel** edges. 

It seems the code works fine to do the plot until it tries to sort the edges of the MultiDiGraph in `digraph2dotlines`  ([here](https://github.com/hklarner/PyBoolNet/blob/d81d8dab0dd7fb2081b13a4fc12f389b3885959a/PyBoolNet/Utility/DiGraphs.py#L118)) where the following `TypeError` is throw: `'<' not supported between instances of 'dict' and 'dict'` 

I managed to make the plot I want by simply removing the "sorted". 
I am breaking something by doing so? :) 

Thanks in advance. 

-----------

Here is a quick example to reproduce the error : 
```python

import networkx as nx
import PyBoolNet

stg = nx.MultiDiGraph()

stg.add_node("a")
stg.add_node("b")
stg.add_node("c")


stg.add_edge("a", "b")
stg.add_edge("a", "b",
             stryle="dotted",
             color="red",
             arrowsize=2
             )


PyBoolNet.StateTransitionGraphs.stg2image(stg, "testMultiDiGraph.png")

```

**Comment by hklarner** [comment]
Good observation! I can confirm that `PyBoolNet.StateTransitionGraphs.stg2image` can plot multi graphs if `sorted` is removed from here

https://github.com/hklarner/PyBoolNet/blob/d81d8dab0dd7fb2081b13a4fc12f389b3885959a/PyBoolNet/Utility/DiGraphs.py#L118

If you want, make the change and create a pull request. I will merge into master.
