### ISSUE TITLE
Value of `primes` in the `*successor_*` functions

### ISSUE THREAD

**Issue by nanls** [hklarner/PyBoolNet#50]
Hi (happy new year ! :partying_face: ),

I just wonder what is the value of  `primes` in the example section of the doctrings of 

- `successor_synchronous`
- `successor_asynchronous`
- `random_successor_mixed`

should be. Also, is it instantiated somewhere to run some kind of tests ? 

I am currently coding for `successor_mixed`* to compute STG with the mixed update scheme and I would like the example I give to be consistent with the ones already given. 

\* Would you be interested by a PR ?

**Comment by hklarner** [comment]
Hi!

the examples in the doc-strings of the three functions are made up to illustrate the type of answer you can expect.

There are unit tests for these functions:

https://github.com/hklarner/PyBoolNet/blob/0dad95f203485efe04e50a64a59f26d7b7d86520/PyBoolNet/Tests/Modules.py#L234-L260

but they are very unspecific - they don't assert the returned values.

By the way, here is an interactive webpage for computing state transitions and interaction for a three variable Boolean network:

- http://page.mi.fu-berlin.de/klarner/iBoolNet/iBoolNet.html


> Would you be interested by a PR ?

sure!
