### ISSUE TITLE
Unable to pass all dependency test in windows

### ISSUE THREAD

**Issue by wilsonwcyiu** [hklarner/PyBoolNet#60]
Dear all,

Does anyone know how to handle this dependency problem? Thanks.
![image](https://user-images.githubusercontent.com/13941660/109502175-f214d000-7a98-11eb-9612-879876ae2986.png)

Wilson

**Comment by hklarner** [comment]
- It looks like the file `eqntott_win64.exe` is missing. I'll fix this asap ad make a new release.
- regarding the the other file, have you installed **grphviz** for windows?
   - https://graphviz.org/download/

**Comment by wilsonwcyiu** [comment]
Yes

**Comment by hklarner** [comment]
ok then it looks like the path in
- https://github.com/hklarner/PyBoolNet/blob/master/Dependencies/win64/settings.cfg

is wrong as well. I'll prepare a branch for you to test..

**Comment by wilsonwcyiu** [comment]
Many thanks for the prompt reply!

**Comment by hklarner** [comment]
I need to set the path to the program `dot` which is part of Graphviz. How do you start `dot` in windows? Is it enough to type `dot`?

**Comment by hklarner** [comment]
do the dependency checks work if you install this branch?

- https://github.com/hklarner/PyBoolNet/tree/bugfix_espresso_windows

```
pip install git+ssh://github.com/hklarner/PyBoolNet@bugfix_espresso_windows
```

**Comment by wilsonwcyiu** [comment]
Hi i have an assignment deadline tonight,  let me try it tomorrow and reply
you. On the other hand,  do you mind if I want to include my lecturer and
TAs in the upcoming mails?  I am a student fro,  Leiden University.
Thanks!

**Comment by hklarner** [comment]
- sure, include any other people
- I would be happy and interested in giving feedback and advice on your application of pyboolnet!
- you could also give a short presentation on your study in our group at the [Freie Universität Berlin](https://www.mi.fu-berlin.de/en/math/groups/dibimath/index.html)
