### ISSUE TITLE
setup.py install_requires pins versions of dependencies

### ISSUE THREAD

**Issue by carissableker** [hklarner/PyBoolNet#67]
Would it be possible to unpin the dependencies in setup.py? 

For example, I need matplotlib 3.4.x in the same environment as PyBoolNet, while PyBoolNet sets matplotlib to only version 3.3.3. 
Work arounds exist , but better practice would be to only specify minimally required dependency versions, and let end users pin their enviroment. 

See https://stackoverflow.com/a/44938662 for an explanation. 

I suggest changing 

https://github.com/hklarner/PyBoolNet/blob/bbb538068a470a593ebe60ede7ce38c900ad7141/setup.py#L63-L68

to (something like):

      install_requires=[
          "networkx>=2.4",
          "matplotlib>=3.3.3",
          "pytest",
          "pyeda>=0.28.0"
      ]

**Comment by hklarner** [comment]
Makes sense. Do you want to send a PR or shall I do it?
