### ISSUE TITLE
Call to NuSMV fails: error while loaded shared library libreadline.so.6 (part 1)

### ISSUE THREAD

**Issue by hklarner** [hklarner/PyBoolNet#7]
error message:

`./NuSMVa: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`

solution for linux available at stackoverflow:

http://stackoverflow.com/questions/23993377/red-language-console-error-libreadline-so-6-cannot-open-shared-object-file

the crucial line:

`sudo apt-get install libreadline6:i386`

an alternative that might also work is

`sudo apt-get install libreadline-dev`

**Comment by bytemains** [comment]
In Fedora, the installation to fix this is:
dnf install compat-readline6
