### ISSUE TITLE
model checking with windows

### ISSUE THREAD

**Issue by hklarner** [hklarner/PyBoolNet#8]
the function `ModelChecking.check_primes(..)` does currently not work for the windows release because NuSMV apparently does not support piping the contents of a file instead of a file name. I am not sure how we can solve this, if anyone has an idea, let me know. The work around is to create the _smv_ file explicitely and do the model checking on that file:

```
>>> ModelChecking.primes2smv(primes, update, init, spec, fname)
>>> answer = ModelChecking.check_smv(fname)
>>> answer, counterex = ModelChecking.check_smv_with_counterexample(fname)
>>> answer, accept = ModelChecking.check_smv_with_acceptingstates(fname)
```

**Comment by hklarner** [comment]
this issue should be fixed for PyBoolNet starting from version > 2.1
the fix uses the `tempfile` to generate temporary file names when checking primes.

**Comment by phenethyl** [comment]
There is still an issue with **check_primes**, **check_primes_with_counterexample** and **check_primes_with_acceptingstates** duo to the /dev/stdin in 2.11.
I also don't see any FnameSMV tempfile generated within the current version, was this pushed?

**Comment by hklarner** [comment]
looks like you are right, the /dev/stdin is still in 2.11. will prepare a new version asap.

**Comment by hklarner** [comment]
`/dev/stdin` is gone, model checking is done with `tempfile`
