### ISSUE TITLE
module 'pyboolnet' has no attribute 'FileExchange'

### ISSUE THREAD

**Issue by stas-g** [hklarner/pyboolnet#86]
hi,

i successfully used PyBoolNet earlier this year but clearly syntax (and even the name of the module) has change in the past couple of months so my previous PyBoolNet code does not work. for example, pyboolnet doesn't have FileExchange function. Unfortunately, the user manual does not reflect these changes so i am not sure which syntax i am now to use to rewrite my previous code. is there a fresh version of the manual somewhere? 

best,
stas

**Comment by hklarner** [comment]
Hi,

yes you are right, the change from 2 to 3 introduced many name changes. This was necessary to make PBN conform with modern PEP-8 coding styles and add type hints for parameters and return values. **Unfortunately I am behind in fixing the documentation**, which is - as you pointed out - broken. Clearly this makes the migration more difficult, I am sorry for that.

I strongly recommend that you use an IDE with autocomplete to navigate through the new package structure, e.g. PyCharm.

The structure can also be seen here:
- https://github.com/hklarner/pyboolnet/tree/master/pyboolnet

The module for files is `file_exchange`.

**Comment by hklarner** [comment]
I hope that typically as a user of PBN the migration consists only of a some "find and replace" edits of your source files, but feel free to ask more questions here about your migration and I'll help you.

**Comment by stas-g** [comment]
many thanks for this! will try your solutions! and knock again in case of troubles... 
hope you have time to update documentation in the near future! big fan of your software (and papers)

best,
stas

**Comment by hklarner** [comment]
Thank you! Yes, I have more motivation now to fix the docs soon..

**Comment by hklarner** [comment]
The reference is mostly back:
- https://pyboolnet.readthedocs.io/en/develop/reference.html
- https://pyboolnet.readthedocs.io/en/master/reference.html
