### ISSUE TITLE
PyBoolNet Questions

### ISSUE THREAD

**Issue by agathat** [hklarner/PyBoolNet#9]
**What was the motivation behind its development? How do you see your tool differing from CellNOpt and GINsim?**

"The motivation behind PyBoolNet was to develop a simple Python interface to Boolean networks that can answer "classical problems". In addition we have implemented algorithms that currently only exist in PyBoolNet, e.g. finding these generalized steady states ("trap spaces") but also NuSMV-a ("model checking with accepting states").

CellNOpt is not a general modeling tool for Boolean networks. It solves a very particular problem: it infers the logical rules of a (Boolean) network from prior knowledge about interactions and time series data.
There are practically no tasks that you can do in PyBoolNet that you can also do in CellNOpt, and the other way around.

GINsim is quiet similar to PyBoolNet. There are some things you can do in GINsim and PyBoolNet. An important difference is that GINsim is meant to be a point and click program (tool with GUI) whereas PyBoolNet is a tool for which you have to write python scripts. The idea is that you can come up with your own work flows and implement them in PyBoolNet.
For example: you can generate several "candidate" networks, e.g. all networks that differ in the shape of a particular signaling cascade, and then find all candidates that can produce certain phenotypes." _Hklarner_

**Is there any easy way to convert back to SMBL-qual data format?**

"Yes, but you have to go via the R package BoolNet. For conversion between SBML-qual and BNET (basic text format) see the BoolNet functions:

loadNetwork(..)
toSBML(..)." _Hklarner_

**How well does PyBoolNet scale with large networks?**

"Depends on what you want to do with it and what "large" is. You can compute steady states for networks with 600 components easily, unless the update functions are particularly evil. You can do model checking for 50 components easily. You can draw interaction graphs or state transition graphs for 3000 nodes easily." _Hklarner_

**Is there a road-map for further development and support of PyBoolNet?**

"I intend to support PyBoolNet in its current form as long as there are questions. Further development is anticipated but there is no strict road map. The next project is about the representation of sets of states." _Hklarner_

**Comment by hklarner** [comment]
@agathat thanks for uploading these!
