### ISSUE TITLE
igraph2image FileNotFoundError

### ISSUE THREAD

**Issue by yzongy** [hklarner/pyboolnet#91]
Hi, I was  running:

```
igraph = primes2igraph(primes)
igraph2image(igraph, "test_simpleModel.pdf")
```

and got this error:

> INFO created None
> Traceback (most recent call last):
>   File "/Users/yzongy/BooleanNetworks/test.py", line 21, in <module>
>     igraph2image(igraph, "test_simpleModel.pdf")
>   File "/Users/yzongy/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pyboolnet/interaction_graphs.py", line 213, in igraph2image
>     digraph2image(igraph, fname_image, layout_engine=layout_engine)
>   File "/Users/yzongy/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pyboolnet/digraphs.py", line 274, in digraph2image
>     proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>   File "/Users/yzongy/.pyenv/versions/3.9.7/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Users/yzongy/.pyenv/versions/3.9.7/lib/python3.9/subprocess.py", line 1821, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/fdp'

I would be very grateful if you could guide me through it. 

Best,

Bill

**Comment by hklarner** [comment]
Hi Bill,

looks like you don't have Graphviz installed. You are on Windows, right?
- https://pyboolnet.readthedocs.io/en/master/installation.html#graphviz

**Comment by yzongy** [comment]
Hi,

Thanks for your quick reply. I am on Mac and have installed graphviz 2.50.0
.

**Comment by hklarner** [comment]
The command `/usr/bin/fdp` is missing. `fdp` is the default layout engine. What happens when you call `fdp` in the terminal? What happens when you call `dot` in the terminal? What happens when you change the layout engine to dot?
```
igraph2image(igraph, "test_simpleModel.pdf", layout_engine="dot")
```

**Comment by yzongy** [comment]
Hi Hannes,

It did work when fdp or dot was called in the terminal, which printed XML
file from a dot file:
$ fdp -Tsvg irma.dot

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
> <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
>  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
> 
> 
> <svg width="191pt" height="180pt"
>  viewBox="0.00 0.00 191.01 180.00" xmlns="http://www.w3.org/2000/svg"
> xmlns:xlink="http://www.w3.org/1999/xlink">
> <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4
> 176)">
> <polygon fill="white" stroke="transparent" points="-4,4 -4,-176
> 187.01,-176 187.01,4 -4,4"/>
> 
> <g id="node1" class="node">
> <title>xA</title>
> <ellipse fill="#f2f2f2" stroke="transparent" cx="67.84" cy="-58.84"
> rx="14.5" ry="14.5"/>
> <text text-anchor="middle" x="67.84" y="-55.14" font-family="Times,serif"
> font-size="14.00">xA</text>
> </g>
>
......
>

So it's quite odd?

Best,

Bill

**Comment by hklarner** [comment]
Right. So you can use pyboolnet to create the dot file and then call `fdp` or `dot` yourself from the command line.

If you want to create the pdf from pyboolnet you need to find out the path for the layout engines e.g. `fdp` and `dot` and make changes to the `settings.cfg` file.

Find out the path to your layout engines by calling `$which fdp` or `$whereis fdp`.

The `settings.cfg` file is in the pyboolnet directory on your computer. You can find out where you have pyboolnet installed by importing pyboolnet and calling `.__file__` on it:

```python
$ python3
>>> import pyboolnet
>>> pyboolnet.__file__
~/lib/python3.8/site-packages/pyboolnet
```

The settings file will then be located in
- `~/lib/python3.8/site-packages/pyboolnet/binaries/settings.cfg`

**Comment by yzongy** [comment]
It works! Thanks for your time and step by step guidance!

Best,

Bill
