### ISSUE TITLE
Error in loading BNet file

### ISSUE THREAD

**Issue by yzongy** [hklarner/pyboolnet#92]
Hi Hannes,

I am loading a model and converting it to primes with bent2primes. But it seems like there was a formatting issue with the input file:
ERROR failed to run bnet2primes: cmd=/Users/yzongy/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pyboolnet/binaries/BNetToPrime/BNetToPrime_mac64, return_code=1, out=b''

How can I get further information on this error and locate the problem in my input file?

Model: [processed_output_boolNet_wildtype_fbcBased.txt](https://github.com/hklarner/pyboolnet/files/8109524/processed_output_boolNet_wildtype_fbcBased.txt)

Best,

Bill

**Comment by carissableker** [comment]
This is not a bnet file -- see here for the documentation: https://pyboolnet.readthedocs.io/en/master/quickstart.html?highlight=bnet#boolean-networks


ANd for examples of the correct format: 
https://github.com/hklarner/pyboolnet/tree/master/pyboolnet/repository

**Comment by hklarner** [comment]
thanks @carissableker for responding!

I agree, [processed_output_boolNet_wildtype_fbcBased.txt](https://github.com/hklarner/pyboolnet/files/8109524/processed_output_boolNet_wildtype_fbcBased.txt), is not a bnet file. Looks like it lists conjunctive conditions that are sufficient for activating components - this also explains, why the same targets appear repeatedly.

@yzongy you should ask the pystablemotifs maintainers how to obtain a valid bnet file.

**Comment by yzongy** [comment]
Thanks for your hints! I have validated the bnet file already, so bnet2Prime is running properly now. But the issue is it takes so long to convert a model with about 3000 nodes to primes:
<img width="506" alt="Screen Shot 2022-02-22 at 11 21 17 PM" src="https://user-images.githubusercontent.com/37186049/155236605-bc9530ed-de0a-47f6-b47d-a7857d65f216.png">

Is there any tips to speed it up?

**Comment by hklarner** [comment]
I think the `BnetToPrime` is pretty competitive in terms of cpu time. The task is linear for the number of components (3000 in your case) and exponential in the number of inputs of each components.

Primes are just a Python dict, so save and load them using the built in json library.

Btw 3000 nodes is a very large model. I've worked with models of about 100 nodes.

**Comment by yzongy** [comment]
Thanks for the hints! 

I tried to split long rules and make the number of components of each rule under 5 by adding new intermediate nodes.

It took significantly less time to run bnet2primes.

Thanks again!
