### ISSUE TITLE
AttributeError: module 'pyboolnet' has no attribute 'file_exchange'

### ISSUE THREAD

**Issue by tlorance** [hklarner/pyboolnet#97]
I know this issue is similar to #86, but I am trying the fix noted there and the fix isn't working either (as seen in the error message "AttributeError: module 'pyboolnet' has no attribute 'file_exchange'").  I struggled to get pyboolnet installed with PyCharm, and so it is quite possible I screwed something up, but pip3 repeatedly tells me that it and its dependencies are installed correctly.  However, I can't follow any of the tests in the Installation part of the documentation because PyBoolNet won't import (I can import pyboolnet) and Tests, tests, FileExchange, and file_exchange are all not attributes of pyboolnet, even though I can find the corresponding .py files in the pyboolnet installation.

Any assistance or guidance you could provide would be appreciated.

**Comment by hklarner** [comment]
Hello,

can you please open a terminal, start the interactive python interpreter, import pyboolnet and paste the whole output here?

**Comment by tlorance** [comment]
The output from that sequence of commands is not unusual:

> ted@TedLnewacbookI9 binaries % python3.9
> Python 3.9.9 (main, Nov 16 2021, 07:33:57) 
> [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pyboolnet
> >>> 

However, if I follow it with an attempt to use the FileExchange feature, per the documentation but with the new names per issue #86 (pyboolnet instead of PyBoolNet, file_exchange instead of FileExchange), I get:

> >>> primes = pyboolnet.file_exchange.bnet2primes(bnet)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'pyboolnet' has no attribute 'file_exchange'
> >>>

In fact, the only attributes I can find for pyboolnet (per PyCharm autocompletion) are: read_version_text(), log, COLORS, UPDATES, VERSION, helpers (pyboolnet), version (pyboolnet), COLORMAP, EXECUTABLES, find_command(name), GRAPHVIZ_LAYOUT_ENGINES, NUSMV_KEYWORDS, read_executables, ROOT_DIR, and read_nusmv_keywords_or_exit().  It seems to me that some link has been broken during my tortured installation process: pyboolnet is convinced that it is installed, but it cannot access its own functions.

**Comment by hklarner** [comment]
how did you install pyboolnet? Can you repeat the installation and copy the output here?

**Comment by tlorance** [comment]
Dear Hannes,
    I am pasting below the output I get now; it is not the output of an install, but it is the output of an install attempt.


***@***.*** pyboolnet % pip3 install git+https://github.com/hklarner/pyboolnet

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

Collecting git+https://github.com/hklarner/pyboolnet

  Cloning https://github.com/hklarner/pyboolnet to /private/var/folders/sx/6qg6wnk93ds0d53ylqrfrh5m0000gp/T/pip-req-build-t4mr3t4u

  Running command git clone -q https://github.com/hklarner/pyboolnet /private/var/folders/sx/6qg6wnk93ds0d53ylqrfrh5m0000gp/T/pip-req-build-t4mr3t4u

  Resolved https://github.com/hklarner/pyboolnet to commit 7aa20da942041cec15da011c136e87a374389c4e

Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.9/site-packages (from pyboolnet==3.0.9) (2.8.4)

Requirement already satisfied: pytest in /usr/local/lib/python3.9/site-packages (from pyboolnet==3.0.9) (7.1.2)

Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.9/site-packages (from pyboolnet==3.0.9) (8.1.3)

Requirement already satisfied: iniconfig in /usr/local/lib/python3.9/site-packages (from pytest->pyboolnet==3.0.9) (1.1.1)

Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.9/site-packages (from pytest->pyboolnet==3.0.9) (21.4.0)

Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.9/site-packages (from pytest->pyboolnet==3.0.9) (1.0.0)

Requirement already satisfied: py>=1.8.2 in /usr/local/lib/python3.9/site-packages (from pytest->pyboolnet==3.0.9) (1.11.0)

Requirement already satisfied: packaging in /usr/local/lib/python3.9/site-packages (from pytest->pyboolnet==3.0.9) (21.3)

Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.9/site-packages (from pytest->pyboolnet==3.0.9) (2.0.1)

Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.9/site-packages (from packaging->pytest->pyboolnet==3.0.9) (3.0.9)

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

WARNING: You are using pip version 21.2.4; however, version 22.1.2 is available.

You should consider upgrading via the ***@***.***/bin/python3.9 -m pip install --upgrade pip' command.

***@***.*** pyboolnet % pip3 show PyBoolNet

Name: pyboolnet

Version: 3.0.9

Summary: Python Toolbox for the generation, manipulation and analysis of Boolean networks.

Home-page: https://github.com/hklarner/pyboolnet

Author: Hannes Klarner

Author-email: ***@***.***

License: UNKNOWN

Location: /Users/ted/Library/Python/3.9/lib/python/site-packages

Requires: click, networkx, pytest

Required-by:

    I originally tried to install pyboolnet from inside PyCharm, but I could not make that work.  However, command line install seemed to work, and I eventually got PyCharm to add the installation location to its path, so now it recognizes pyboolnet, but it seems like an “empty package”, with few or no executable commands or functions.

  Thank you,
  Ted Lorance

Ted Lorance
Professor of Organic Chemistry, Chair of Eng. Phys., Comp. Sci., and Applied Math.
T 714.619.6467  vanguard.edu
55 Fair Drive, Costa Mesa, CA 92626<webextlink://55%20Fair%20Drive,%20Costa%20Mesa,%20CA%2092626>

 [https://gallery.mailchimp.com/356d77963084daf8f0b949266/images/f89a7ecd-4378-4c40-be70-a98b31bfcf92.jpg]


From: hklarner ***@***.***>
Date: Tuesday, July 19, 2022 at 11:29 PM
To: hklarner/pyboolnet ***@***.***>
Cc: Lorance, Ted ***@***.***>, Author ***@***.***>
Subject: Re: [hklarner/pyboolnet] AttributeError: module 'pyboolnet' has no attribute 'file_exchange' (Issue #97)

how did you install pyboolnet? Can you repeat the installation and copy the output here?

**Comment by hklarner** [comment]
Hey @tlorance I am not sure how I can help you. Please install via pip3 if you're on Linux. If you're on a May I can't help you, unfortunately. Here is how I install pyboolnet and make sure it has access to `file_exchange`:

```
$ pip3 install git+https://github.com/hklarner/pyboolnet
...
Successfully built pyboolnet
Installing collected packages: pyboolnet
Successfully installed pyboolnet-3.0.9

$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyboolnet
>>> from pyboolnet import file_exchange
>>> 
```
