### ISSUE TITLE
yield mixed successors

### ISSUE THREAD

**Issue by nanls** [hklarner/pyboolnet#98]
Hallo!

As mentioned in the documentation of `successors_mixed`, there are 2^n mixed successors for a given state (n being the number of variables). In a recent work, I had to compute the mixed successors for n up to 60, and the current code was exhausting my RAM...

I ended up doing a quick and dirty hack by just replacing the list built in `successors_mixed` by a generator, and I would be happy to open a PR about this if you are interested. However, the current version of the hack might break compatibility, for example if someone stores the result of  `successors_mixed` to use it several times. 

Hence, I have the following proposition:
What about having a dedicated function (`successors_mixed_yield`) yielding the successors, and `successors_mixed` reconstructing a list out of it?

---
By the way, it is a pleasure to work with pyboolnet v3. I really appreciate the refactoring and code style. Cheers for all the work! :sparkles:

**Comment by hklarner** [comment]
Hey Athénaïs, nice to hear from you!

How about you add a parameter `yield: bool = True` to `successors_mixed`?


> By the way, it is a pleasure to work with pyboolnet v3. I really appreciate the refactoring and code style. Cheers for all the work!

:heart:

**Comment by nanls** [comment]
Sure! But in any case, I do not really see how to completely get rid of the `successors_mixed_yield` function, as adding a `yield` statement to `successors_mixed` would automatically transform it to a generator. :confused:

Would something like this be ok?
```python
def successors_mixed(n, yield_ = False) :

    def successors_mixed_yield (n) : 
        for i in range (n) : 
            yield i
     
    if yield_ : 
        return successors_mixed_yield(n) 
    return list(successors_mixed_yield(n))

```

**Comment by hklarner** [comment]
That's right.

So add `successors_mixed_yield` outside of `successors_mixed`, no need to create a function within a function.

Otherwise, looks good.
